[package]
name = "ambient-weather-local"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4"
env_logger = "0.9"
serde = { version = "1", features = [ "derive" ] }
time = { version = "0.3", features = [ "parsing", "serde" ] }
tracing = "0.1"
tracing-actix-web = "0.7"
