use serde::Deserialize;

#[derive(Debug, Default, Deserialize)]
#[serde(default)]
pub struct AmbientWeatherReport {
    #[serde(rename = "stationtype")]
    pub station_type: String,
    #[serde(rename = "PASSKEY")]
    pub passkey: String,
    pub dateutc: String,
    pub aqi_pm25: Option<f64>,
    pub aqi_pm25_24h: Option<f64>,
    pub aqi_pm25_24h_aqin: Option<f64>,
    pub aqi_pm25_aqin: Option<f64>,
    pub baromabsin: Option<f64>,
    pub baromrelin: Option<f64>,
    pub batt_25: Option<f64>,
    pub batt_co2: Option<f64>,
    pub batt_lightning: Option<f64>,
    pub battin: Option<f64>,
    pub battout: Option<f64>,
    pub co2_in_24h_aqin: Option<f64>,
    pub co2_in_aqin: Option<f64>,
    pub dailyrainin: Option<f64>,
    pub eventrainin: Option<f64>,
    pub hourlyrainin: Option<f64>,
    pub humidity: Option<f64>,
    pub humidityin: Option<f64>,
    pub lightning_day: Option<f64>,
    pub maxdailygust: Option<f64>,
    pub monthlyrainin: Option<f64>,
    pub pm10_in_24h_aqin: Option<f64>,
    pub pm10_in_aqin: Option<f64>,
    pub pm25: Option<f64>,
    pub pm25_24h: Option<f64>,
    pub pm25_in_24h_aqin: Option<f64>,
    pub pm25_in_aqin: Option<f64>,
    pub pm_in_humidity_aqin: Option<f64>,
    pub pm_in_temp_aqin: Option<f64>,
    pub solarradiation: Option<f64>,
    pub tempf: Option<f64>,
    pub tempinf: Option<f64>,
    pub uv: Option<f64>,
    pub weeklyrainin: Option<f64>,
    pub winddir: Option<f64>,
    pub winddir_avg10m: Option<f64>,
    pub windgustmph: Option<f64>,
    pub windspdmph_avg10m: Option<f64>,
    pub windspeedmph: Option<f64>,
    pub yearlyrainin: Option<f64>,
}
